In [1]:
# import statements
import pandas as pd
import numpy as np

# create spotify_df using the spotify_data.csv file
spotify_df = pd.read_csv("spotify_data.csv")
spotify_df

,artist_followers,genres,artist_name,artist_popularity,track_name,track_popularity,release_date,danceability,loudness,energy_lvl
0,248568,pop & rock,Raghu Dixit,52,Eno Ide,29,2008,0.639,-11.386,Low energy
1,248568,pop & rock,Raghu Dixit,52,Ee Tanuvu Ninnade,28,2008,0.508,-10.192,High energy
2,248568,pop & rock,Raghu Dixit,52,Munjaane Manjalli,42,1/5/2010,0.390,-8.671,High energy
3,248568,pop & rock,Raghu Dixit,52,Gudugudiya Sedi Nodo,38,2010,0.676,-5.043,High energy
4,248568,pop & rock,Raghu Dixit,52,Ambar,38,2010,0.507,-6.902,Low energy
...,...,...,...,...,...,...,...,...,...,...
245097,66464,miscellaneous,Keira Knightley,53,Coming Up Roses,51,7/1/2014,0.477,-5.323,High energy
245098,4491,miscellaneous,IVOXYGEN,51,Young Kid,57,2/28/2020,0.782,-7.077,High energy
245099,12742,pop,MAY-A,55,Apricots,54,10/6/2020,0.482,-5.808,High energy
245100,12742,pop,MAY-A,55,Time I Love to Waste,59,2/18/2021,0.650,-5.094,High energy
245101,73350,miscellaneous,90sFlav,59,Call me,70,2/9/2018,0.748,-12.074,Low energy

In [2]:
# Which three genres have the highest danceability on average?
display(spotify_df.groupby("genres")[["danceability"]].mean())

               danceability
genres
country            0.601226
electronic         0.608183
folk               0.525161
hip hop            0.718769
hoerspiel          0.661333
jazz               0.517055
latin              0.608025
metal              0.419201
miscellaneous      0.574622
pop                0.588275
pop & rock         0.545256
rap                0.726907
rock               0.520274

rap has the highest danceability, followed by hip hop, which is then followed by hoerspiel

In [3]:
# Use 'track_popularity' to create a new column 'track_popularity_level' by binning track_popularity into 3 bins. 
# Label the bins 'low', 'medium' and 'high' (Hint: Use pd.cut).
spotify_df["track_popularity_level"] = pd.cut(spotify_df["track_popularity"], 3, labels=["low", "medium", "high"])
spotify_df

,artist_followers,genres,artist_name,artist_popularity,track_name,track_popularity,release_date,danceability,loudness,energy_lvl,track_popularity_level
0,248568,pop & rock,Raghu Dixit,52,Eno Ide,29,2008,0.639,-11.386,Low energy,low
1,248568,pop & rock,Raghu Dixit,52,Ee Tanuvu Ninnade,28,2008,0.508,-10.192,High energy,low
2,248568,pop & rock,Raghu Dixit,52,Munjaane Manjalli,42,1/5/2010,0.390,-8.671,High energy,medium
3,248568,pop & rock,Raghu Dixit,52,Gudugudiya Sedi Nodo,38,2010,0.676,-5.043,High energy,medium
4,248568,pop & rock,Raghu Dixit,52,Ambar,38,2010,0.507,-6.902,Low energy,medium
...,...,...,...,...,...,...,...,...,...,...,...
245097,66464,miscellaneous,Keira Knightley,53,Coming Up Roses,51,7/1/2014,0.477,-5.323,High energy,medium
245098,4491,miscellaneous,IVOXYGEN,51,Young Kid,57,2/28/2020,0.782,-7.077,High energy,medium
245099,12742,pop,MAY-A,55,Apricots,54,10/6/2020,0.482,-5.808,High energy,medium
245100,12742,pop,MAY-A,55,Time I Love to Waste,59,2/18/2021,0.650,-5.094,High energy,medium
245101,73350,miscellaneous,90sFlav,59,Call me,70,2/9/2018,0.748,-12.074,Low energy,high

In [4]:
# Create a pivot table to show the average danceability of tracks grouped by genre and track 
# popularity level on the rows and separated by energy levels in the columns. 
# Show the margin averages. What does this pivot table tell you about the relationship between 
# popularity and danceability for a) country tracks and b) electronic tracks?
spotify_pivot = spotify_df.pivot_table("danceability", index="track_popularity_level", columns="genres", aggfunc="mean", margins=True)
display(spotify_pivot)

genres,country,electronic,folk,hip hop,hoerspiel,jazz,latin,metal,miscellaneous,pop,pop & rock,rap,rock,All
track_popularity_level,,,,,,,,,,,,,,
low,0.622341,0.560941,0.507033,0.713259,0.667190,0.509522,0.609837,0.372714,0.542152,0.552077,0.537532,0.763519,0.513670,0.544395
medium,0.589853,0.618853,0.554102,0.717589,0.654612,0.546702,0.604369,0.425332,0.597717,0.610653,0.550522,0.722407,0.524509,0.584088
high,0.574035,0.668111,0.516588,0.741451,NaN,0.563469,0.682256,0.473948,0.635447,0.633909,0.577335,0.712530,0.543611,0.620674
All,0.601226,0.608183,0.525161,0.718769,0.661333,0.517055,0.608025,0.419201,0.574622,0.588275,0.545256,0.726907,0.520274,0.567780

This shows me that less popular country tracks are more danceable than more popular country tracks, while the opposite applies for electronic tracks. More popular electronic tracks are more danceable than less popular electronic tracks.

In [5]:
# What percentage of all the unique tracks are contributed by the top 3 artists of each genre, 
# where the top artists are based on artist_popularity, and the unique tracks are based on unique values of track_name?
top_artists_genre = spotify_df.groupby(["genres", "artist_name"])[["artist_popularity"]].max()
top_artists_track_count = spotify_df.groupby(["genres", "artist_name"])[["track_name"]].nunique()
display(top_artists_genre)
display(top_artists_track_count)

                        artist_popularity
genres  artist_name
country Alan Jackson                   76
        Blake Shelton                  77
        Brad Paisley                   71
        Brett Young                    73
        Casey Donahew                  60
...                                   ...
rock    Ã“scar ChÃ¡vez                   51
        Ä°kiye On Kala                  61
        Ð”Ð”Ð¢                            52
        Ð”Ð°Ð¹Ñ‚Ðµ Ñ‚Ð°Ð½Ðº (!)                 58
        ã‚ªãƒ¬ãƒ³ã‚¸ã‚¹ãƒ‘ã‚¤ãƒ‹ã‚¯ãƒ©ãƒ–                    57

[11946 rows x 1 columns]

                        track_name
genres  artist_name
country Alan Jackson            61
        Blake Shelton           16
        Brad Paisley            16
        Brett Young              5
        Casey Donahew            3
...                            ...
rock    Ã“scar ChÃ¡vez            33
        Ä°kiye On Kala            8
        Ð”Ð”Ð¢                     52
        Ð”Ð°Ð¹Ñ‚Ðµ Ñ‚Ð°Ð½Ðº (!)          22
        ã‚ªãƒ¬ãƒ³ã‚¸ã‚¹ãƒ‘ã‚¤ãƒ‹ã‚¯ãƒ©ãƒ–              1

[11946 rows x 1 columns]